# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  catalog.api:
    build:
      context: "/Users/miguelbtcode/Cursos/6.Microservices-dotnet/aspnetmicroservices/src"
      dockerfile: "Services/Catalog/Catalog.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/Catalog.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    image: "catalogapi:dev"
    ports: []
    volumes:
    - "/Users/miguelbtcode/Cursos/6.Microservices-dotnet/aspnetmicroservices/src/Services/Catalog/Catalog.API:/app:rw"
    working_dir: "/app"
